// let states = {
//     "All": "All",
//     "Alabama": "Alabama",
//     "Alaska": "Alaska",
//     "Arizona": "Arizona",
//     "Arkansas": "Arkansas",
//     "California": "California",
//     "Colorado": "Colorado",
//     "Connecticut": "Connecticut",
//     "Delaware": "Delaware",
//     "Florida": "Florida",
//     "Georgia": "Georgia",
//     "Hawaii": "Hawaii",
//     "Idaho": "Idaho",
//     "Illinois": "Illinois",
//     "Indiana": "Indiana",
//     "Iowa": "Iowa",
//     "Kansas": "Kansas",
//     "Kentucky": "Kentucky",
//     "Louisiana": "Louisiana",
//     "Maine": "Maine",
//     "Maryland": "Maryland",
//     "Massachusetts": "Massachusetts",
//     "Michigan": "Michigan",
//     "Minnesota": "Minnesota",
//     "Mississippi": "Mississippi",
//     "Missouri": "Missouri",
//     "Montana": "Montana",
//     "Nebraska": "Nebraska",
//     "Nevada": "Nevada",
//     "New Hampshire": "New Hampshire",
//     "New Jersey": "New Jersey",
//     "New Mexico": "New Mexico",
//     "New York": "New York",
//     "North Carolina": "North Carolina",
//     "North Dakota": "North Dakota",
//     "Ohio": "Ohio",
//     "Oklahoma": "Oklahoma",
//     "Oregon": "Oregon",
//     "Pennsylvania": "Pennsylvania",
//     "Rhode Island": "Rhode Island",
//     "South Carolina": "South Carolina",
//     "South Dakota": "South Dakota",
//     "Tennessee": "Tennessee",
//     "Texas": "Texas",
//     "Utah": "Utah",
//     "Vermont": "Vermont",
//     "Virginia": "Virginia",
//     "Washington": "Washington",
//     "West Virginia": "West Virginia",
//     "Wisconsin": "Wisconsin",
//     "Wyoming": "Wyoming"
// }

const states_list = [
    'All',
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
]

const min_prices = [
    0,
    5000,
    10000,
    15000,
    20000,
    25000,
    30000,
    35000,
    40000,
    45000,
    50000,
    55000,
    60000,
    65000,
    70000,
    75000,
    80000
]

const max_prices = [
    0,
    5000,
    10000,
    15000,
    20000,
    25000,
    30000,
    35000,
    40000,
    45000,
    50000,
    55000,
    60000,
    65000,
    70000,
    75000,
    80000
]

export {states_list, min_prices, max_prices};